name: google_cloud_datastore
version: 0.4.0+1
author: Thomas Stephenson <ovangle@gmail.com>
description: Connect to a google cloud datastore via the protocol buffer api
homepage: http://github.com/ovangle/googleclouddatastore
dependencies:
  google_oauth2_client: '>=0.3.7 <0.4.0'
  http: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  protobuf: '>=0.3.3 <0.4.0'
  quiver: '>=0.18.0 <0.19.0'
dev_dependencies:
  protobuf_builder: '>=0.1.0 <0.2.0'
  protoc_plugin:
    git: https://github.com/dart-lang/dart-protoc-plugin.git
  unittest: any
